---
# * Don't forget comment uslesess block for you

- name: Configure system started # Updating apt cache
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: start



- name: Configure wallpaper
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: wallpaper

- name: Configure base
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: base

- name: Configure Apps
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: app

- name: Git Configure
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: git

- name: Configure Docker packages # Install Docker & Docker-compose from official repo
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: docker

- name: Configure packages from additional repo
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: additional_repo

- name: Configure packages by snap
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: snap

- name: Configure packages by flatpak
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: flatpak

- name: Configure custom packages
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: custom



- name: Configure system finished # Clear dnf cache & useless dependencies
  hosts: localhost
  tasks:
  - include_role:
      name: fedora
      tasks_from: end
