- name: Configure system started
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: start



- name: Configure SWAP file on server
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: swapfile

- name: Configure base system packages
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: base

- name: Configure SDK & DevTools
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: sdk

- name: Configure SSH
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: ssh

- name: Install Docker & Docker-compose from official repo
  hosts: servers
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: docker

# - name: Configure Docker Swarm
#   hosts: swarm
#   tasks:
#   - include_role:
#       name: ubuntu-server
#       tasks_from: docker-swarm

- name: Install & configure GitLab-runner packages
  hosts: servers
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: gitlab-runner

- name: Install and configure WebServers
  hosts: webservers
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: webservers

- name: Install and configure databases
  hosts: databases
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: databases



- name: Configure system finished (Clear apt cache & useless dependencies)
  hosts: all
  tasks:
  - include_role:
      name: ubuntu-server
      tasks_from: end
