- name: Install Redis
  when: redis_install is defined and redis_install | bool
  become: true
  ansible.builtin.apt:
    name: redis
    state: present
- name: Configure Redis password
  when: redis_install is defined and redis_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^# requirepass foobared"
    line: "requirepass {{ redis_password }}"
    owner: redis
    group: redis
    mode: "0640"
- name: Configure Redis listen interface
  when: redis_install is defined and redis_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^bind 127.0.0.1 ::1"
    line: "# bind 127.0.0.1 ::1"
    owner: redis
    group: redis
    mode: "0640"
- name: Disable autostart & stop Redis
  when: redis_install is defined and redis_install | bool
  become: true
  ansible.builtin.service:
    name: redis-server
    enabled: false
    state: stopped

- name: Install PostgreSQL
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - postgresql-common
      - postgresql-client
      - postgresql-client-common
      - python3-psycopg2
    # - python3-ipaddr

- name: Start PostgreSQL service
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Change postgres password
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_method: enable
  ansible.builtin.command: sudo su postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';\""

- name: Collect PostgreSQL version
  when: postgres_install is defined and postgres_install | bool
  community.postgresql.postgresql_info:
    login_host: "127.0.0.1"
    login_user: "postgres"
    login_password: "{{ postgres_password }}"
    filter: ver*
  register: postgres_version

- name: Configure PostgreSQL allow connection
  when: postgres_install is defined and postgres_install | bool
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgres_version.version.major }}/main/pg_hba.conf
    contype: host
    users: all
    source: "0.0.0.0/0"
    databases: all
    method: md5
    create: true

- name: Configure PostgreSQL listen interface
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Configure PostgreSQL shared buffers
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^shared_buffers = 128MB"
    line: "shared_buffers = {{ (ansible_facts['memtotal_mb'] * 0.25) | int | abs }}MB"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Configure PostgreSQL work mem
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^#work_mem = 4MB"
    line: "work_mem = 16MB"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Configure PostgreSQL work mem
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^#maintenance_work_mem = 64MB"
    line: "maintenance_work_mem = 500MB"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Configure PostgreSQL effective_io_concurrency
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^#effective_io_concurrency = 1"
    line: "effective_io_concurrency = 100"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Configure PostgreSQL random_page_cost
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version.version.major }}/main/postgresql.conf
    regexp: "^#random_page_cost = 4.0"
    line: "random_page_cost = 1.1"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Set PostgreSQL listen interface
  when: postgres_install is defined and postgres_install | bool
  become: true
  community.postgresql.postgresql_set:
    login_host: "127.0.0.1"
    login_user: "postgres"
    login_password: "{{ postgres_password }}"
    name: listen_addresses
    value: "*"

- name: Reload PostgreSQL configuration
  when: postgres_install is defined and postgres_install | bool
  community.postgresql.postgresql_query:
    login_host: "127.0.0.1"
    login_user: "postgres"
    login_password: "{{ postgres_password }}"
    db: postgres
    query: "SELECT pg_reload_conf();"

- name: Enable autostart & start PostgreSQL service
  when: postgres_install is defined and postgres_install | bool
  become: true
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: restarted

- name: Check postgres user SSH dir
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_user: postgres
  ansible.builtin.file:
    path: "/var/lib/postgresql/.ssh"
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: "0775"
- name: Inspect postgres user authorized_keys
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_user: postgres
  ansible.builtin.file:
    path: "/var/lib/postgresql/.ssh/authorized_keys"
    state: touch
    force: false
    owner: "postgres"
    group: "postgres"
    mode: "0664"
- name: Inspect postgres user ssh-config
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_user: postgres
  ansible.builtin.file:
    path: "/var/lib/postgresql/.ssh/config"
    state: touch
    force: false
    owner: "postgres"
    group: "postgres"
    mode: "0664"
- name: Inspect postgres user SSH key
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_user: postgres
  community.crypto.openssh_keypair:
    path: "/var/lib/postgresql/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
    owner: "postgres"
    group: "postgres"
    mode: "0600"

- name: Add a backuper public keys
  when: postgres_install is defined and postgres_install | bool
  become: true
  become_user: postgres
  ansible.builtin.lineinfile:
    path: /var/lib/postgresql/.ssh/authorized_keys
    line: "{{ backuper_ssh_public_key }}"
    state: present
    create: false

- name: Install MySQL
  become: true
  when: mysql_install is defined and mysql_install | bool
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - default-mysql-server
      - default-mysql-client
      - python3-pymysql

- name: Start MySQL service
  become: true
  when: mysql_install is defined and mysql_install | bool
  ansible.builtin.service:
    name: mysql
    state: started

- name: Set MySQL root Password
  ignore_errors: true
  become: true
  when: mysql_install is defined and mysql_install | bool
  community.mysql.mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    # login_password: "{{ mysql_root_password }}"
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present

- name: Configure listen interface
  become: true
  when: mysql_install is defined and mysql_install | bool
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address		= 127.0.0.1"
    line: "bind-address		= 0.0.0.0"
    owner: root
    group: root
    mode: "0644"
- name: Configure listen mysqlx interface
  become: true
  when: mysql_install is defined and mysql_install | bool
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^mysqlx-bind-address	= 127.0.0.1"
    line: "mysqlx-bind-address	= 0.0.0.0"
    owner: root
    group: root
    mode: "0644"

- name: Disable autostart & stop MySQL service
  become: true
  when: mysql_install is defined and mysql_install | bool
  ansible.builtin.service:
    name: mysql
    state: stopped
    enabled: false

# - name: Add ClickHouse GPG key
#   become: true
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: E0C56BD4
# - name: Add ClickHouse repo
#   become: true
#   apt_repository:
#     repo: "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/"
#     state: present
# - name: Install ClickHouse
#   become: true
#   apt:
#     name: "{{ packages }}"
#     state: present
#     update_cache: true
#   vars:
#     packages:
#       - clickhouse-server
#       - clickhouse-client
# - name: Configure ClickHouse user
#   become: true
#   template:
#     src: roles/server-ubuntu/templates/clickhouse_user.xml.j2
#     dest: /etc/clickhouse-server/users.d/{{ clickhouse_user }}.xml
# - name: Disable autoload & stop ClickHouse service
#   become: true
#   service:
#     name: clickhouse-server
#     state: stopped
#     enabled: false

- name: Create non-privileged database user
  become: true
  ansible.builtin.user:
    name: "{{ database_user }}"
    password_lock: true
    state: present
    shell: /bin/bash
    system: false
    createhome: true
    home: "/home/{{ database_user }}"

- name: Check user SSH dir
  become: true
  ansible.builtin.file:
    path: "/home/{{ database_user }}/.ssh"
    state: directory
    owner: "{{ database_user }}"
    group: "{{ database_user }}"
    mode: "0775"

- name: Inspect user authorized_keys
  become: true
  ansible.builtin.file:
    path: "/home/{{ database_user }}/.ssh/authorized_keys"
    state: touch
    force: false
    owner: "{{ database_user }}"
    group: "{{ database_user }}"
    mode: "0664"

- name: Inspect user ssh-config
  become: true
  ansible.builtin.file:
    path: "/home/{{ database_user }}/.ssh/config"
    state: touch
    force: false
    owner: "{{ database_user }}"
    group: "{{ database_user }}"
    mode: "0664"

- name: Inspect user SSH key
  become: true
  community.crypto.openssh_keypair:
    path: "/home/{{ database_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
    owner: "{{ database_user }}"
    group: "{{ database_user }}"
    mode: "0600"
