- name: Install DevTools
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ansible
      - build-essential
      - git
      - watch
      - cmake
      - ninja-build
      - gcc
      - clang
      - libblkid-dev
      - liblzma-dev
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
      - python3
      - python3-pip
      - python3-dev
      - python-dev
      - python-pexpect
      - pipenv
      - virtualenv
      - cmake

- name: Update pip
  become: true
  ignore_errors: true
  pip:
    name:
      - pip
    state: latest

- name: Install Python modules
  pip:
    name: pexpect
