- name: Install Nginx
  become: true
  apt: 
    name: nginx-full
    state: present
- name: Disable autoload & stop Nginx
  become: true
  service:
    name: nginx
    enabled: no
    state: stopped

- name: Install Apache
  become: true
  apt: 
    name: apache2
    state: present
- name: Disable autoload & stop Apache
  become: true
  service:
    name: apache2
    enabled: no
    state: stopped

- name: Install CertBot
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - certbot
    - python3-certbot-nginx

- name: Check LetsEncrypt dir
  file: 
    path: "/var/www/letsencrypt"
    state: directory
    mode: "0777"

- name: Creates a cron task for certbot renew certs
  cron:
    name: renew certs
    state: present
    minute: 0
    hour: 0
    weekday: 1
    user: root
    job: 'certbot renew --non-interactive --quiet --agree-tos --register-unsafely-without-email --no-eff-email --post-hook "nginx -s reload"'
