---

- name: Install browsers
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - firefox
      - chromium
      - torbrowser-launcher
      # - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb # ! Optional. Proprietary.
