---

- name: Install file managing & share packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - transmission
      - syncthing
      - filezilla
      - meld
      - onionshare
      - persepolis
