---

- name: Create user GIT dir
  file:
    path: "/home/{{ os_user }}/git"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: "0755"
  become: true
  become_user: "{{ os_user }}"

- name: Create git lib dir
  file:
    path: "{{ git_lib }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: "0777"
