---

- name: Install Podman packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - podman
      - podman-docker
      - podman-plugins
      - podman-compose
      - buildah
