---

- name: Install Java v8 & v11
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      # - java-1.8.0-openjdk
      # - java-1.8.0-openjdk-devel
      - java-11-openjdk
      - java-11-openjdk-devel

- name: Install DevTools
  dnf: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "@Development Tools"
      - "@development-tools"
      - git
      - ansible
      - cmake
      - ninja-build
      - gcc
      - clang
      - golang
      - jq
      - python3
      - python3-pip
      - python3-devel

- name: Install PostgreSQL packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - postgresql-server
- name: Disable autoload & stop Postgres service
  service:
    name: postgresql
    state: stopped
    enabled: no

- name: Install MySQL packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - community-mysql
      - community-mysql-server
- name: Disable autoload & stop MySQL service
  service:
    name: mysqld
    state: stopped
    enabled: no

- name: Install Redis
  dnf:
    name: redis
    state: present
- name: Disable autoload & stop Redis
  service:
    name: redis
    enabled: no
    state: stopped

- name: Install Nginx packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - nginx-all-modules
- name: Disable autoload & stop Nginx
  service:
    name: nginx
    enabled: no
    state: stopped
