[servers]
master-01 ansible_host=
; worker-01 ansible_host=
; database-01 ansible_host=

[webservers]
master-01 ansible_host=

[databases]
; database-01 ansible_host=

; [swarm]
; master-01 ansible_host= role=manager label=web
; worker-01 ansible_host= role=worker label=app

[all:vars]
ansible_user=root

server_user="server-user"
docker_user="docker-user"
database_user="db-user"

backuper_ssh_public_key=""

# Configuring docker swarm cluster
is_swarm=false

# All config will be reset
fresh_configure=true
# swapfile in MB
swapfile_size=1000
# Force resize swapfile
swapfile_resize=false


redis_install=false
redis_password=

postgres_install=false
postgres_password=postgres

mysql_install=false
mysql_root_password=mysql

clickhouse_user=click_user
clickhouse_password=
clickhouse_public=true

gitlab_runner_shell=false
gitlab_runner_in_docker=false
gitlab_runner_reg_token=
gitlab_runner_description=
gitlab_runner_tag=
