---
- name: Install Apache Directory Studio
  unarchive:
    src: '{{ Apache_Directory_Studio_URL }}'
    dest: /opt/
    remote_src: yes

- name: Create Apache Directory Studio link into Launcher
  template:
    src: ApacheDirectoryStudio.j2
    dest: "/home/{{ os_user }}/.local/share/applications/ApacheDirectoryStudio.desktop"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: '0777'
