---

- name: Add Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
- name: Check lsb_release
  command: "lsb_release -cs"
  register: lsb_release
- name: Add Docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ lsb_release.stdout }} stable"
    filename: docker
    state: present

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add the user Docker groups
  user:
    name: "{{ os_user }}"
    groups: docker
    append: yes
