---

- name: Install system snap packages
  snap:
    name: "{{ packages }}"
    state: present
    classic: no
  vars:
    packages:
    - core

- name: Install develop snap packages with classic
  snap:
    name: "{{ packages }}"
    state: present
    classic: yes
  vars:
    packages:
    - pycharm-community

# - name: Install system snap packages
#   snap:
#     name: "{{ packages }}"
#     state: present
#     classic: no
#   vars:
#     packages:
#     - kdiskmark

# - name: Install network snap packages
#   snap:
#     name: "{{ packages }}"
#     state: present
#     classic: no
#   vars:
#     packages:
#     - ipfs-desktop
