---

- name: Tap a Homebrew repository
  community.general.homebrew_tap:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - homebrew/cask
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - homebrew/core
      - homebrew/services

- name: Tap a Heroku repository
  community.general.homebrew_tap:
    name: heroku/brew
    state: present

# # * Tempalte for add new Tap
# - name: Tap a Homebrew repository using url, state present
#   community.general.homebrew_tap:
#     name: example/brew
#     url: 'https://example.com/dist/brew'