---

- name: Add VScode GPG key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
- name: Add VScode repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: Update cache after update repo
  apt:
    update_cache: yes

- name: Install VScode
  apt:
    name: code
    state: present
