---
- name: Install flatpak
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Add Flathub repo
  command: "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Install Jitsi Meet
  flatpak:
    name: org.jitsi.jitsi-meet
    state: present
