---
- name: Install flatpak
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Add Flathub repo
  command: "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Install Postman
  flatpak:
    name: com.getpostman.Postman
    state: present

- name: Install Zoom
  flatpak:
    name: us.zoom.Zoom
    state: present
- name: Install Skype
  flatpak:
    name: com.skype.Client
    state: present
- name: Install Slack
  flatpak:
    name: com.slack.Slack
    state: present
- name: Install MS Teams
  flatpak:
    name: com.microsoft.Teams
    state: present
- name: Install Jitsi Meet
  flatpak:
    name: org.jitsi.jitsi-meet
    state: present

# Office
- name: Install OnlyOffice
  flatpak:
    name: org.onlyoffice
    state: present
- name: Install Obsidian # ! Proprietary
  flatpak:
    name: md.obsidian.Obsidian
    state: present
