---

- name: Install system snap packages
  snap:
    name: "{{ packages }}"
    state: present
    classic: no
  vars:
    packages:
    - kdiskmark

- name: Install develop snap packages
  snap:
    name: "{{ packages }}"
    state: present
    classic: no
  vars:
    packages:
    - ngrok
