---

- name: Allow snapd
  file:
    dest: /etc/apt/preferences.d/nosnap.pref
    state: absent

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install ansible-galaxy community.general collection
  become: true
  command: ansible-galaxy collection install community.general
