---
- name: Install system
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - pacaur
    - git
    - vim
    - ansible
    - htop
    - jq
    - transmission-qt
    - syncthing
    - jdk11-openjdk
    - jre11-openjdk
    - vagrant
    - docker
    - containerd
    - cmake
    - ninja

- name: Install wine
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - playonlinux
    - wine
    - wine-gecko
    - wine-mono
    - lib32-vkd3d
    - vkd3d

- name: Install libvirt & virt-manager
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - qemu
    - libvirt
    - ebtables
    - virt-manager
    - bridge-utils

- name: Enable libvirt service
  service: 
    name: libvirtd
    state: started
    enabled: yes

- name: Install virtualbox
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - virtualbox-ext-vnc
    - virtualbox-guest-iso
    - virtualbox-host-dkms
    - virtualbox-sdk

- name: Install browsers 
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
    - chromium

- name: Install text editor & IDE
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - libreoffice
    - code
    - kate

- name: Install Remote utils
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - remmina

- name: Install media editor
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - blender
    - gimp
    - inkscape
    - vlc
    - obs-studio

- name: Install Social
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - element-desktop
    - telegram-desktop
    - jami-gnome

