---

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gufw
      - gnome-tweaks
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - gnupg-agent
      - software-properties-common
      - tor
      - vim
      - htop
      - net-tools
      - keepassxc
      - wireshark

- name: Install Remote utils
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
