---
# ! PPA
- name: Add PPA repo for Cryptomator
  apt_repository:
    validate_certs: no
    repo: "ppa:sebastian-stenzel/cryptomator"
    state: present

- name: Install cryptomator
  apt:
    name: cryptomator
    state: present

# - name: Add PPA repo for Persepolis
#   apt_repository:
#     validate_certs: no
#     repo: "ppa:persepolis/ppa"
#     state: present
# - name: Install Persepolis
#   apt:
#     name: persepolis
#     state: present
