---
# ! PPA
- name: Add PPA repo for cryptomator
  apt_repository:
    validate_certs: no
    repo: "ppa:sebastian-stenzel/cryptomator"
    state: present

- name: Install cryptomator
  apt:
    name: cryptomator
    state: present
