---

- name: Install Java
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-11-jdk
      - openjdk-11-jre

- name: Install DevTools
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - git
      - ansible
      - watch
      - cmake
      - ninja-build
      - gcc
      - clang
      - libgtk-3-dev
      - libblkid-dev
      - liblzma-dev
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
      - python3
      - python3-pip
      - python-dev
      - redis
      - wireshark

- name: Disable Redis
  service:
    name: redis-server
    enabled: no
    state: stopped
