---

- name: Install Java v8 & v11
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-8-jdk
      - openjdk-8-jre
      - openjdk-11-jdk
      - openjdk-11-jre

- name: Install DevTools
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - git
      - ansible
      - watch
      - cmake
      - ninja-build
      - gcc
      - clang
      - libgtk-3-dev
      - libblkid-dev
      - liblzma-dev
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
      - jq
      - python3
      - python3-pip
      - python-dev
      - wireshark

- name: Install Redis
  apt:
    name: redis
    state: present

- name: Enable Redis
  service:
    name: redis
    enabled: yes
    state: started
